version: 2.1

jobs:
  # Build Job
  build:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            if [ -f requirements.txt ]; then
            pip install -r requirements.txt
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Check Installed Dependencies
          command: pip list

  # Test Job
  test:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: |
            if [ -f requirements.txt ]; then
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python manage.py test

  # Deploy Job
  deploy:
    docker:
      - image: cimg/python:3.11.5
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Now it's deploying ..."


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main

      - test:
          requires:
            - build
          filters:
            branches:
              only: main
          
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main


